// <auto-generated />
using System;
using ISD.Audit.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISD.Audit.Infrastructure.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260819164553_AddAuditProcessDefinitionsAndNullableSessionId")]
    partial class AddAuditProcessDefinitionsAndNullableSessionId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISD.Audit.Domain.Models.ProcessDefinition", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsFinalStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("ProcessId");

                    b.HasIndex("ProcessName", "StepName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Process_StepName");

                    b.HasIndex("ProcessName", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_Process_StepOrder");

                    b.ToTable("ProcessDefinition", "audit");

                    b.HasData(
                        new
                        {
                            ProcessId = 1,
                            CreatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinalStep = false,
                            ProcessName = "Registration",
                            StepName = "SendRegistrationOTPAsync",
                            StepOrder = 1
                        },
                        new
                        {
                            ProcessId = 2,
                            CreatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinalStep = false,
                            ProcessName = "Registration",
                            StepName = "RegisterAnonymousAsync",
                            StepOrder = 2
                        },
                        new
                        {
                            ProcessId = 3,
                            CreatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinalStep = false,
                            ProcessName = "Registration",
                            StepName = "AddAddressInfoAsync",
                            StepOrder = 3
                        },
                        new
                        {
                            ProcessId = 4,
                            CreatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinalStep = false,
                            ProcessName = "Registration",
                            StepName = "AddPersonalDataAsync",
                            StepOrder = 4
                        },
                        new
                        {
                            ProcessId = 5,
                            CreatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinalStep = false,
                            ProcessName = "Registration",
                            StepName = "UpdatePersonalDocAsync",
                            StepOrder = 5
                        },
                        new
                        {
                            ProcessId = 6,
                            CreatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFinalStep = true,
                            ProcessName = "Registration",
                            StepName = "AddSelfie",
                            StepOrder = 6
                        });
                });

            modelBuilder.Entity("ISD.Audit.Domain.Models.UserJourneyLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("SessionId")
                        .HasMaxLength(150)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LogId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_UserJourneyLogs_SessionId");

                    b.HasIndex("ProcessName", "CreatedAt")
                        .HasDatabaseName("IX_UserJourneyLogs_ProcessName_CreatedAt");

                    b.ToTable("UserJourneyLogs", "audit", t =>
                        {
                            t.HasCheckConstraint("CK_UserJourneyLogs_Status", "Status IN ('Success', 'Failed')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
