<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ISD.Audit.Infrastructure\ISD.Audit.Infrastructure.csproj" />
    <ProjectReference Include="..\InteriorHub.Application\InteriorHub.Application.csproj" />
    <ProjectReference Include="..\InteriorHub.Infrastructure\InteriorHub.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modular\Auth\AuthModule.Infrastructure\AuthModule.Infrastructure.csproj" />
  </ItemGroup>

</Project>
